// AUTO-GENERATED by scripts/scrape-merge-tactics.mjs — re-run to update

export interface Ruler {
  key: string;
  name: string;
  description: string;
  modifierName: string;
  modifierDescription: string;
  skins: string[];
}

export const RULERS: Record<string, Ruler> = {
  royale_king: {
    key: "royale_king",
    name: "Royale King",
    description: "After nearly a decade in the Arena, the King is nothing if not flexible with his battle strategies. The madness of Merge Tactics will prove to be his greatest feat yet!",
    modifierName: "Royal Commission",
    modifierDescription: "Losing grants you +4-8 Elixir",
    skins: ["Marble King", "Velvet King", "Ghoul King", "Santa King"],
  },
  spirit_empress: {
    key: "spirit_empress",
    name: "Spirit Empress",
    description: "Who needs to heal when you can wield spirits with sheer force of will? This sly little rebel oozes intellect, battling boldly in hopes of discovering the true nature of her power.",
    modifierName: "Fusion Foresight",
    modifierDescription: "Every merge grants you +1 bonus Elixir",
    skins: ["Ivy Empress", "Auric Empress", "Wushi Empress", "Astral Empress"],
  },
  goblin_queen: {
    key: "goblin_queen",
    name: "Goblin Queen",
    description: "She has travelled across the Emerald Sea to wreak havoc in the Arena. The only thing that calms her wrath are the Baby Goblins, but they're not here...",
    modifierName: "Greener Grin",
    modifierDescription: "Defeating an enemy results in a 33% chance of gaining a Goblin",
    skins: ["Jade Queen", "Chaos Queen", "Malevolent Queen", "Serpentine Queen"],
  },
  elixir_loong: {
    key: "elixir_loong",
    name: "Elixir Loong",
    description: "Freshly emerged from the River of Golden Elixir, this lucky dragon brings honor to all those who fight alongside him",
    modifierName: "Endless Spring",
    modifierDescription: "Gain +1 Elixir per round and +1 Team Size",
    skins: ["Spirit Loong", "Lava Loong", "Aqua Loong"],
  },
  battle_machine: {
    key: "battle_machine",
    name: "Battle Machine",
    description: "Master Builder has been tweaking this machine for years. Finally, his most prized invention is Arena-ready, and he'll make sure everyone knows that Builder mean boss.",
    modifierName: "Building Master",
    modifierDescription: "Brings one random 1/2/3/4-Star building into battle in Rounds 1/3/5/8, -1 max Team Size.",
    skins: ["Zebrawood Machine", "Scheme Machine", "Forge Machine"],
  },
  echo_sage: {
    key: "echo_sage",
    name: "Echo Sage",
    description: "The ability to echo oneself must be cultivated over centuries of less triumph than defeat. Only one has ever studied under this being and, even as a Champion, he only managed to scrape the surface",
    modifierName: "Striking Clone",
    modifierDescription: "Summons The Echo who knocks out the nearest enemy, or enemies, after charging",
    skins: ["Echo Sage", "Sunlight Sage", "Starborn Sage", "Spectral Sage"],
  },
  dagger_duchess: {
    key: "dagger_duchess",
    name: "Dagger Duchess",
    description: "This dedicated dame does nothing but sharpen her daggers and prepare for victory. Any troop that dares to approach her finds themselves fleeing the tower in fear. Princess practices, but Duchess dominates.",
    modifierName: "Dagger Donation",
    modifierDescription: "Leaves you a Dagger to equip to any troop",
    skins: ["Disguised Duchess", "Duchess of Hearts", "Crystalline Duchess"],
  },
};

export function getRulerKeys(): string[] { return Object.keys(RULERS); }
export function getRulerByKey(key: string): Ruler | undefined { return RULERS[key]; }

export function rulerImagePath(key: string): string {
  return `/Rulers/${key.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("-")}.webp`;
}

/** Path to the default (base) ruler skin image used for pixel/display purposes. */
export function defaultRulerImagePath(key: string): string {
  const folder = key.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("_");
  return `/Rulers/${folder}/Default_${folder}.png`;
}
